In [1]:
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np
%matplotlib inline


In [2]:
df = pd.read_csv("C:\\Users\\AtulKumar\\Downloads\\diabetes.csv")
df.head(3)

Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
0            6      148             72             35        0  33.6   
1            1       85             66             29        0  26.6   
2            8      183             64              0        0  23.3   

   DiabetesPedigreeFunction  Age  Outcome  
0                     0.627   50        1  
1                     0.351   31        0  
2                     0.672   32        1

In [14]:
df.shape

(768, 9)

In [25]:
df1=df[~(df.BloodPressure==0)]
df1.shape

(733, 9)

In [27]:
df1.Glucose.unique()

array([148,  85, 183,  89, 137, 116,  78, 197, 125, 110, 168, 139, 189,
       166, 118, 107, 103, 115, 126,  99, 196, 119, 143, 147,  97, 145,
       117, 109, 158,  88,  92, 122, 138, 102,  90, 111, 180, 133, 106,
       171, 159, 146,  71, 101, 176, 150,  73, 187, 100, 105,  44, 141,
       114,  95, 129,  79,   0,  62, 112, 113,  83, 136,  80, 123,  81,
       134, 142, 144,  93, 163, 151,  96, 155,  76, 160, 124, 162, 132,
       120, 173, 170,  84, 128, 108, 154,  57, 156, 153, 188, 152, 131,
       104,  75, 179, 130,  87, 194, 181, 184, 140, 177,  74, 164,  91,
       165,  86, 193, 191, 161,  77, 182, 157, 178,  61,  98, 127,  82,
        72, 172,  94, 135, 175, 195,  68, 186, 198, 121,  67, 174, 167,
       199,  56, 169, 149,  65, 190], dtype=int64)

In [30]:
df2=df1[~(df1.Glucose==0)]
df2.shape

(728, 9)

In [38]:
df2.Age.unique()

array([50, 31, 32, 21, 33, 30, 26, 53, 54, 34, 57, 59, 51, 27, 41, 29, 43,
       22, 38, 60, 28, 45, 35, 46, 56, 37, 48, 40, 25, 58, 42, 44, 39, 36,
       24, 23, 61, 69, 62, 55, 65, 47, 52, 66, 49, 63, 67, 81, 64, 70, 68],
      dtype=int64)

In [43]:
X=df2.drop('Outcome',axis=1)
X.head(2)

Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
0            6      148             72             35        0  33.6   
1            1       85             66             29        0  26.6   

   DiabetesPedigreeFunction  Age  
0                     0.627   50  
1                     0.351   31

In [44]:
Y=df2.Outcome
Y.head(2)

0    1
1    0
Name: Outcome, dtype: int64

In [39]:
from sklearn.model_selection import train_test_split

In [60]:
x_train,x_test,y_train,y_test = train_test_split(X,Y,train_size=.8)

In [61]:
from sklearn.model_selection import cross_val_score
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier


In [62]:
cross_val_score(LogisticRegression(),X,Y,cv=3)

C:\Users\AtulKumar\anaconda3\Lib\site-packages\sklearn\linear_model\_logistic.py:458: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
C:\Users\AtulKumar\anaconda3\Lib\site-packages\sklearn\linear_model\_logistic.py:458: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
 

array([0.77366255, 0.74897119, 0.78512397])

In [63]:
cross_val_score(SVC(),X,Y,cv=3)

array([0.72427984, 0.73251029, 0.77272727])

In [64]:
cross_val_score(RandomForestClassifier(),X,Y,cv=3)

array([0.74074074, 0.75720165, 0.81818182])

In [65]:
cross_val_score(DecisionTreeClassifier(),X,Y,cv=3)

array([0.66666667, 0.67489712, 0.68595041])